### ISSUE TITLE
isnan problem in Matlab

### ISSUE THREAD

**Issue by CicoZhang** [marcelm82/IKAP#1]
I am not a Matlab user, so when I run the code for a try, I am just confronted with some errors; could you please give me some help?

> > [AP,AP_tab,K,cost,mincost]=FitActivities(a,data_red,kin,1,1000)
> > Error using ComputeCostGlobal (line 25)
> > Undefined function 'isnan' for input arguments of type 'cell'.
> > 
> > Error in FitActivities>@(ts)(ComputeCostGlobal(ts,tk,a,data_red,ncon)) (line 36)
> >           [ts,J1]=fmincon(@(ts)(ComputeCostGlobal(ts,tk,a,data_red,ncon)), ts, [], [], [], [], lb1, ub1, [], options);
> > 
> > Error in fmincon (line 543)
> >       [initVals.f,initVals.g] = feval(funfcn{3},X,varargin{:});
> > 
> > Error in FitActivities (line 30)
> > parfor i=1:iter
> > 
> > Caused by:
> >     Failure in initial user-supplied objective function evaluation. FMINCON cannot continue.

When I reproduce it following the tutorial, the problem still persists. I am using Matlab 2015b

**Comment by marcel-mischnik** [comment]
Hi Cico,

could you maybe send me your data_red variable as .mat file? I will then
try to reproduce your error.

Best regards,
Marcel

2016-01-21 23:01 GMT+01:00 Cico notifications@github.com:

**Comment by CicoZhang** [comment]
Hey, Marcel:
I have attached the data here.
Actually, I just reproduce the method using the data in the paper and making the phosphositePlus data myself, the problem still persists.

[data_red.zip](https://github.com/marcel-mischnik/IKAP/files/100695/data_red.zip)

**Comment by marcel-mischnik** [comment]
The mitosis raw data in the supplement on the Bioinformatics homepage
include additional columns that should be removed before starting the
algorithm. I have attached the readily prepared data-mit, as well as the
data_red variable. You can also use the files in the supplement archive on
github. Anyway, you should fit over all conditions in order to gain better
estimates for the affinity parameters, and even though 1000 iterations will
give you a good coverage of the parameter space, it will probably take way
too long. So, if you just want to test the method you should write
something like:

 [AP,AP_tab,K,cost,mincost]=FitActivities(a,data_red,kin,6,5);

2016-01-22 12:39 GMT+01:00 Cico notifications@github.com:

**Comment by CicoZhang** [comment]
Hi, Marcel:
Thank you for your help, I have pinpointed the problem. It works now.  Actually, I have a another question:
What do these data values  (negative, positive or NaN) stand for (they are measured values, are they)? 
![image](https://cloud.githubusercontent.com/assets/11710225/12530280/0bb0e396-c1da-11e5-82df-4c819e80af13.png)

In the formula below, K and p will be evaluated, will they?
![image](https://cloud.githubusercontent.com/assets/11710225/12530315/dac23d3c-c1db-11e5-8aaa-a574d2f97be5.png)
If so, in the paper (as follows), 'a' is mentioned to be 'mostly known by proteomics data'.
![image](https://cloud.githubusercontent.com/assets/11710225/12530319/0181f688-c1dc-11e5-81a4-9a5015f15230.png)
I cannot make out why 'a' is mentioned if K is evaluated and not calculated based on 'a'? 

What is the measured value 'P'?

**Comment by marcel-mischnik** [comment]
Hi Cico,
the values correspond to the log2 intensity of the phosphopeptide
normalized by the protein abundance. The columns stand for the six cell
cycle stages G1, G1/S, early S, late S, G2 and M.

2016-01-23 14:04 GMT+01:00 Cico notifications@github.com:

**Comment by CicoZhang** [comment]
Hi, Marcel:
Thank you for your reply. 
You mean the log2 intensity of phosphopeptide over the protein abundance the phosphopeptide belongs to, is it right?

By the way, in the matlab codes, the formula is not used directly, since k is trained directly in the grid search, is it?

![](https://cloud.githubusercontent.com/assets/11710225/12530319/0181f688-c1dc-11e5-81a4-9a5015f15230.png)

Best wishes,

Cico

**Comment by marcel-mischnik** [comment]
Yes and yes :).

2016-02-02 16:50 GMT+01:00 Cico notifications@github.com:

**Comment by CicoZhang** [comment]
Thanks and thanks. :+1:
